# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development: 
  adapter: postgresql 
  encoding: utf8 
  database: searchthesales_development 
  username: donald
  host: localhost
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: searchthesales_test
  pool: 5
  port: 5432
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  Host: 172.17.42.1
  database: storeluv_production
  Port: 49155
  User: 'root'
  Password: 'G7MVKtvQraeJg6RY'
  Database: 'db'
  Url: 'postgres://root:G7MVKtvQraeJg6RY@172.17.42.1:49155/db' 
  