mailer:
	confirmation_instructions:
		subject: 'Confirmation instructions'
	reset_password_instructions:
		subject: 'Reset password instructions'
	unlock_instructions:
		subject: 'Unlock Instructions'